<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sophie Shi, Keon Bruce Dibley, Colin Tien Nguyen, Pramukh Shubh Shankar">
<meta name="dcterms.date" content="2024-10-30">

<title>Biomarkers of ASD</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Biomarkers of ASD</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sophie Shi, Keon Bruce Dibley, Colin Tien Nguyen, Pramukh Shubh Shankar </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Updated</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 30, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>Based on the studies on biomarkers of ASD done by Hewitson et al., we use the whole dataset to further explore the impacts of various modifications. In part one, we examine the distribution of raw values for a sample of proteins including HXK2, IL-4, PAI-1, PGP9.5, and STK16. In part two, we continue working on exploratory analysis of outlying values before conducting the outlier trimming in the preprocessing. In part three, we repeated the selection methods which are random forests, multiple testing, and correlation tests on a training dataset with modifications. From each of the selection methods, we choose 25 top predictive proteins and use a fuzzy intersection to form our protein panel. In part four, we use a simpler panel to examine the corresponding accuracy.</p>
</section>
<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">Dataset</h2>
<p>Serum samples from 76 boys with ASD and 78 typically developing (TD) boys, 18 months-8 years of age, were analyzed to identify possible early biological markers for ASD. The ASD group was comprised of 76 subjects with a mean age of 5.6 years (SD 1.7 years). The TD group was comprised of 78 subjects with a mean age of 5.7 years (SD 2.0 years).&nbsp;Measured variables include ADOS and 1317 proteins. For the ASD group, ADOS diagnostic algorithms consisting of two behavioral domains: Social Affect (SA) and Restricted and Repetitive Behaviors (RRB) were used to determine an ADOS total score, which provides a continuous measure of overall ASD symptom severity. All subjects were healthy, defined as being fever-free for 24 hours, and presenting with no clinical symptoms. A fasting blood draw was performed on ASD and TD subjects between the hours of 8–10 am in a 3.5 ml Serum Separation Tube using standard venipuncture technique.&nbsp;</p>
<p>In the published data, 192 proteins failed to pass quality control (QC). After removing these proteins, 1,125 proteins were analyzed. The protein abundance data were normalized by taking log10 transform and then z-transformation. To deal with outliers, any z-transformed values less than -3 and greater than 3 were clipped to -3 and 3, respectively.&nbsp;</p>
</section>
<section id="summary-of-published-analysis" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-published-analysis">Summary of published analysis</h2>
<p>Hewitson et al.&nbsp;first used the R package ‘randomForest’ to train the RF models and calculate feature importance. They chose MeanDecreaseGini as the surrogate representing a protein’s importance in predicting ASD versus TD. With normalized data, they trained an RF model 1000 times. Each protein’s importance value was averaged over the 1000 runs. The 10 proteins with the highest averaged importance values were chosen for the RF-based prediction model. For multiple testing, Hewitson et al.&nbsp;used t-tests to select the 10 proteins with the most highly significant t-test values for the prediction model. Thirdly, a correlation approach was used to calculate each protein’s correlation with ADOS total scores (SA + RRB) as a measure of ASD severity. Based upon the absolute values of each protein’s correlation coefficient, the 10 most highly correlated proteins were selected as the correlation-based predictive proteins. After identifying the top-10 predictive proteins from each of the 3 models, they found 5 proteins that were common to each method used which are considered ‘core’ proteins. A logistic regression model was used with datasets based upon the RF model, the t-test model and the correlation model, taking the subjects’ assigned group (ASD or TD) as output variables to evaluate the 13 additional proteins.&nbsp;</p>
<p>Five core proteins mitogen-activated protein kinase 14 (MAPK14), immunoglobulin D (IgD), dermatopontin (DERM), ephrin type-B receptor 2 (EPHB2), and soluble urokinase-type plasminogen activator receptor (suPAR) are used. And four additional proteins are selected for their resulted increase in AUC when being added which are receptor tyrosine kinase-like orphan receptor 1 [ROR1], platelet receptor Gl24 [GI24], eukaryotic translation initiation factor 4H [elF-4H], and arylsulfatase B [ARSB]. Combining the 5 core proteins with the additional 4 proteins resulted in an AUC = 0.860±0.064, with a sensitivity = 0.833±0.118, and specificity = 0.846±0.118, and represents the 9 optimal proteins (AUC_Optimal).</p>
</section>
<section id="findings" class="level2">
<h2 class="anchored" data-anchor-id="findings">Findings</h2>
<section id="impact-of-preprocessing-and-outliers" class="level3">
<h3 class="anchored" data-anchor-id="impact-of-preprocessing-and-outliers">Impact of preprocessing and outliers</h3>
<p>Tasks 1</p>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-2_8200de615170a2b4788655e1b262eb19">
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The data seems to be heavily skewed to the right. By doing a log transform, the skewness of the data would be lessened, making the patterns easier to analyze as most models assume constant variance.</p>
<p>Task 2</p>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-3_9a1bb68408b9afb3e7a175e4619b8ad8">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 154 × 2
   group total_outliers
   &lt;chr&gt;          &lt;dbl&gt;
 1 ASD                9
 2 ASD               10
 3 ASD               12
 4 ASD               17
 5 ASD                4
 6 ASD               10
 7 ASD                6
 8 ASD                6
 9 ASD              126
10 ASD               10
# ℹ 144 more rows</code></pre>
</div>
<div class="cell-output-display">
<p><img src="report_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We found that the average amount of outliers for ASD is 13.2 and 17.6 for TD. Also, we can see that very subject had at least 1 outlier except for 2. 5 subjects had a dispropportionate amount of outliers (&gt;100), and 2 of these subjects were ASD while 4 were TD. As you can see in our graph, outliers didn’t appear more frequent in one group in regards to another.</p>
</section>
<section id="methodlogical-variations" class="level3">
<h3 class="anchored" data-anchor-id="methodlogical-variations">Methodlogical variations</h3>
<p>Task 3</p>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-4_82ad0ddf38060eb4856edd8bb3788cd5">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  protein data              
  &lt;chr&gt;   &lt;list&gt;            
1 CHIP    &lt;tibble [123 × 2]&gt;
2 CEBPB   &lt;tibble [123 × 2]&gt;
3 NSE     &lt;tibble [123 × 2]&gt;
4 PIAS4   &lt;tibble [123 × 2]&gt;</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Top 10 proteins for multiple testing:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "DERM"            "Calcineurin"     "RELT"            "CXCL16, soluble"
 [5] "TGF-b R III"     "M2-PK"           "EPHB2"           "C1QR1"          
 [9] "FCN1"            "IGFBP-4"        </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Top 10 proteins for random forest:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "TGF-b R III"                     "EPHB2"                          
 [3] "SNP25"                           "Aflatoxin B1 aldehyde reductase"
 [5] "MAPK14"                          "CD27"                           
 [7] "GDF-11/8"                        "PPID"                           
 [9] "Gelsolin"                        "DERM"                           </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Top 10 proteins for correlation method:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "TRAIL R4"   "EFNB1"      "PDK1"       "IL-1F8"     "Cystatin-S"
 [6] "SMOC1"      "Apo E"      "CO8A1"      "SPTA2"      "LIGHT"     </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "DERM"        "TGF-b R III" "EPHB2"      </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 sensitivity binary         0.75 
2 specificity binary         0.733
3 accuracy    binary         0.742
4 roc_auc     binary         0.763</code></pre>
</div>
</div>
<p>By only applying the selection methods to training dataset, there are only three core proteins which are “DERM”, “TGF-b R III”, “EPHB2”. We are able to get a similar sensitivity, specificity, accuracy and roc_auc values which are around 0.7.</p>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-5_2ec68dd0fe4ec6814b868e9e421a301a">
<div class="cell-output cell-output-stdout">
<pre><code>    ASD TD class.error
ASD  48 28   0.3684211
TD   17 61   0.2179487</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 76 × 1,319
   group  ados    CHIP  CEBPB     NSE   PIAS4 `IL-10 Ra`   STAT3    IRF1 `c-Jun`
   &lt;chr&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1 ASD       8  0.335   0.520 -0.554   0.650     -0.358   0.305  -0.484    0.309
 2 ASD      21 -0.0715  1.01   3       1.28      -0.133   1.13    0.253    0.408
 3 ASD      12 -0.406  -0.531 -0.0592  1.13       0.554  -0.334   0.287   -0.845
 4 ASD      20 -0.102  -0.251  1.47    0.0773    -0.705   0.893   2.61    -0.372
 5 ASD      22 -0.395  -0.536  0.0410 -0.299     -0.830   0.899   1.01    -0.843
 6 ASD      17 -0.126   1.27  -0.892   0.239     -0.344   0.216   0.211    0.221
 7 ASD      15  0.486   0.748 -1.09    0.462      0.570  -0.0682  1.01     1.21 
 8 ASD      10 -0.990  -1.10   0.231  -0.885     -0.151   0.0307 -0.0346  -0.891
 9 ASD      22 -0.108   3      2.32    3          2.76    1.70    0.209    3    
10 ASD      17  0.485  -0.234 -0.697  -0.286      0.0331  1.01   -0.248   -0.293
# ℹ 66 more rows
# ℹ 1,309 more variables: `Mcl-1` &lt;dbl&gt;, OAS1 &lt;dbl&gt;, `c-Myc` &lt;dbl&gt;,
#   SMAD3 &lt;dbl&gt;, SMAD2 &lt;dbl&gt;, `IL-23` &lt;dbl&gt;, PDGFRA &lt;dbl&gt;, `IL-12` &lt;dbl&gt;,
#   STAT1 &lt;dbl&gt;, STAT6 &lt;dbl&gt;, LRRK2 &lt;dbl&gt;, Osteocalcin &lt;dbl&gt;, `IL-5` &lt;dbl&gt;,
#   GPDA &lt;dbl&gt;, IgA &lt;dbl&gt;, LPPL &lt;dbl&gt;, HEMK2 &lt;dbl&gt;, PDXK &lt;dbl&gt;, TLR4 &lt;dbl&gt;,
#   REG4 &lt;dbl&gt;, `HSP 27` &lt;dbl&gt;, `YKL-40` &lt;dbl&gt;, `Alpha enolase` &lt;dbl&gt;,
#   `Apo L1` &lt;dbl&gt;, CD38 &lt;dbl&gt;, CD59 &lt;dbl&gt;, FABPL &lt;dbl&gt;, `GDF-11` &lt;dbl&gt;, …</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "DERM"           "RELT"           "Calcineurin"    "IgD"           
 [5] "PTN"            "FSTL1"          "MAPK2"          "TGF-b R III"   
 [9] "MMP-2"          "gp130, soluble" "Notch 1"        "ALCAM"         
[13] "MATN2"         </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 sensitivity binary         0.812
2 specificity binary         0.867
3 accuracy    binary         0.839
4 roc_auc     binary         0.946</code></pre>
</div>
</div>
<p>To see whether choosing a larger number of predictive proteins would impact our results, we decided to select the top 25 proteins from random forest and t tests and found the metrics on the resulting model. After intersecting, we got a larger model of 13 proteins: “DERM”, “RELT”, “Calcineurin”, “IgD”, “PTN”, “FSTL1”, “MAPK2”, “TGF-b R III”, “MMP-2”, “gp130, soluble”, “Notch 1”, “ALCAM”, and “MATN2”. With this panel, we fitted a logistic regression model, which reported a higher ROC_AUC of 0.946.</p>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-6_dacab0a12d6ea6bc5c3e646bdfed2991">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "DERM"        "IgD"         "TGF-b R III" "MAPK14"      "FSTL1"      </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  .metric     .estimator .estimate
  &lt;chr&gt;       &lt;chr&gt;          &lt;dbl&gt;
1 sensitivity binary         0.75 
2 specificity binary         0.8  
3 accuracy    binary         0.774
4 roc_auc     binary         0.888</code></pre>
</div>
</div>
<p>To perform a fuzzy intersection to combine top predictive proteins across our selection methods, we normalized random forest importance scores and converted p-values from our t tests so that we could compare the results from the methods. We then found the minimum of these values for each protein and selected a threshold for which variables we would want to include in a new regression analysis. Through this regression we found a ROC_AUC of 0.888, which was lower than the original analysis, indicating that our model performed slightly worse, but comparably.</p>
</section>
<section id="improved-classifier" class="level3">
<h3 class="anchored" data-anchor-id="improved-classifier">Improved classifier</h3>
<p>Task 4</p>
<div class="cell" data-hash="report_cache/html/unnamed-chunk-7_29423dd25ad2b870f79d47c6209be6f6">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric  .estimator .estimate
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 accuracy binary         0.871</code></pre>
</div>
</div>
<p>First, we split our data into training and testing sets, with 80% of the data being training data. Next, we performed cross validation on the training set to get a panel of proteins. Then, we fit a binomial generalized linear model to this panel of proteins and evaluated our metrics. We reported an accuracy of 0.871 on our panel of proteins.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>